# Generated by Django 2.1.7 on 2019-06-21 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=4)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(max_length=15)),
                ('education', models.CharField(choices=[('UE', 'Uneducated'), ('F_E', '5th to 8th'), ('N_T', '9th to 10th'), ('E_T', '11th to 12th'), ('ITI', 'ITI'), ('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('PT', 'Polytechnic'), ('DP', 'Diploma'), ('BE', 'B.E'), ('ME', 'M.E'), ('BSC', 'B.Sc'), ('MSC', 'M.Sc'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BT', 'B.Tech'), ('MT', 'M.Tech'), ('MAD', "Master's Degree"), ('BAD', "Bachelor's Degree")], max_length=20)),
                ('skillset', models.CharField(max_length=255)),
                ('experince', models.CharField(blank=True, max_length=2)),
                ('identification', models.CharField(max_length=50)),
                ('resume', models.FileField(blank=True, upload_to='resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_gst_no', models.CharField(max_length=50)),
                ('company_cin', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='employerprofileinfo',
            unique_together={('company_gst_no', 'company_cin', 'location')},
        ),
    ]
