# Generated by Django 2.1.7 on 2019-06-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('skillset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region')),
            ],
        ),
        migrations.AddField(
            model_name='employeeprofileinfo',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AddField(
            model_name='city1',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillset.State'),
        ),
        migrations.AddField(
            model_name='employeeprofileinfo',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skillset.State'),
        ),
    ]
